spring:
  datasource:
    url: jdbc:h2:mem:currentDb
    driver-class-name: org.h2.Driver
    username: pranonraian
    password: Test123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true